//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVisualEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnovaCard
    {
        public int Id { get; set; }
        public string CardName { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaViaje { get; set; }
        public double CreditoDisponible1 { get; set; }
        public double CostoPasaje { get; set; }
    }
}
